Compile paraview v5.11.0
SENSEI-insitu/SENSEI pull request #108
Opened 2023-03-23 18:23 UTC by danlipsa

2023-03-23 18:23 UTC, danlipsa commented
@c-wetterer-nelson @patrickoleary Please review

2023-03-23 20:00 UTC, burlen requested changes
please use vtk version to select vtk features since those can be used without PV

2023-03-23 20:03 UTC, danlipsa commented on sensei/CatalystAnalysisAdaptor.cxx
> +#endif
This is the full message of the deprecation:   "vtkPVConfig.h is deprecated. Please include `vtkPVVersion.h`, `pqQtConfig.h`, or `pqQtWidgetConfig.h` instead.")

2023-03-23 20:05 UTC, danlipsa commented on sensei/CatalystAnalysisAdaptor.cxx
> +#endif
So it seems the original PVConfig had some QT stuff in it.

2023-03-23 23:01 UTC, danlipsa commented
@burlen Any idea what is the issue with ecp-sdk-integration failing tests?

2023-03-24 16:18 UTC, burlen commented
> @burlen Any idea what is the issue with ecp-sdk-integration failing tests?
All the tests fail like this:
```
mpiexec noticed that process rank 1 with PID 0 on node 277cde878462 exited on signal 4 (Illegal instruction).
```
I have no idea why that would be. @kwryankrattiger? @patrickoleary?

2023-03-27 12:36 UTC, danlipsa commented
@burlen Lets merge this - the ecp errors seem unrelated. Thanks!

2023-03-31 15:55 UTC, danlipsa commented
@burlen Ping.

2023-03-31 20:16 UTC, burlen commented
@danlipsa OK, merging. added you to the team, in the future you can do it on your own

2023-03-31 20:16 UTC, merged

2023-03-31 20:32 UTC, danlipsa commented
Great. Thanks!